##############################################################################
#
# Assignment and Constraints Quartus TCL script for design C:\FPGA\DE1\PruebaDE1\EDIF\PruebaDE1.edf
#
# Generated by Celoxica Hardware Compiler (Version 3.5.2841)
# Timestamp 2015 11 5 13 0 35
#
##############################################################################


# Set family and part
set_global_assignment -name FAMILY "CYCLONE II"
set_global_assignment -name DEVICE "EP2C20F484C7"

# Set compilation options
set_global_assignment -name ALLOW_POWER_UP_DONT_CARE Off
set_global_assignment -name AUTO_PACKED_REGISTERS Normal


############################### IO assignments ###############################

set_location_assignment PIN_L1 -to PIN_L1
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_L1
set_location_assignment PIN_L2 -to PIN_L2
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_L2
set_location_assignment PIN_M1 -to PIN_M1
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_M1
set_location_assignment PIN_M2 -to PIN_M2
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_M2
set_location_assignment PIN_U11 -to PIN_U11
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_U11
set_location_assignment PIN_U12 -to PIN_U12
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_U12
set_location_assignment PIN_W12 -to PIN_W12
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_W12
set_location_assignment PIN_V12 -to PIN_V12
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_V12
set_location_assignment PIN_M22 -to PIN_M22
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_M22
set_location_assignment PIN_L21 -to PIN_L21
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_L21
set_location_assignment PIN_L22 -to PIN_L22
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_L22
set_location_assignment PIN_Y21 -to PIN_Y21
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_Y21
set_location_assignment PIN_Y22 -to PIN_Y22
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_Y22
set_location_assignment PIN_W21 -to PIN_W21
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_W21
set_location_assignment PIN_W22 -to PIN_W22
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_W22
set_location_assignment PIN_V21 -to PIN_V21
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_V21
set_location_assignment PIN_V22 -to PIN_V22
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_V22
set_location_assignment PIN_U21 -to PIN_U21
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_U21
set_location_assignment PIN_U22 -to PIN_U22
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_U22


############################# Timing requirements ############################

